name: GitHub Box

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: master

jobs:
  update-gist:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: yg/gh-box@v1.0.2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 3753e51aab929a084a77e14c52a2864b
          CONSIDER_PRIVATE: true
